version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "LimonTH"
    assignees:
      - "LimonTH"
    ignore:
      - dependency-name: "com.github.cabaletta.baritone:baritone-api"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    labels:
      - "ci"
      - "automated"
    reviewers:
      - "LimonTH"
    assignees:
      - "LimonTH"
